/*
 * shared_resource.h
 *
 *  Created on: Sep 20, 2023
 *      Author: Admin
 */

#ifndef _SHARED_RESOURCE_H_
#define _SHARED_RESOURCE_H_

typedef enum{
	BATSEL_MODE_AUTO,
	BATSEL_MODE_BAT1,
	BATSEL_MODE_BAT2,
} BATSEL_MODE_E;

typedef enum {
	MAX1538_STATE_IDLE,
	MAX1538_STATE_DISCHARGE_A,
	MAX1538_STATE_DISCHARGE_B,
	MAX1538_STATE_AC_ADAPTER,
	MAX1538_STATE_AIRLINE,
	MAX1538_STATE_RELEARN_A,
	MAX1538_STATE_RELEARN_B,
	MAX1538_STATE_CHARGE_A,
	MAX1538_STATE_CHARGE_B,
} MAX1538_STATE_E;


#endif /* _SHARED_RESOURCE_H_ */
